-- -- Tabnine: local small-model ghost-text completion (IntelliCode-style —
-- -- on-device inference on the free tier, no per-token API cost). Suggestions
-- -- render as virtual text independent of blink.cmp's own completion menu.
-- --
-- -- Unlike lazy.nvim/packer, vim.pack.add has no `build`/`do` hook, but this
-- -- plugin needs one: the actual TabNine.exe completion engine isn't in the
-- -- git repo, it's fetched from update.tabnine.com by a post-install script.
-- -- Run once after cloning (and again after any update):
-- --   powershell.exe -ExecutionPolicy Bypass -File .\dl_binaries.ps1
-- -- from `<stdpath data>/site/pack/core/opt/tabnine-nvim`. Already done as
-- -- part of this install; TabNine.exe confirmed present under `binaries/`.
--
-- vim.pack.add { 'https://github.com/codota/tabnine-nvim' }
--
-- require('tabnine').setup {
--   disable_auto_comment = true,
--   -- <C-j>/<C-k>/<Tab> are all already taken (Roslyn inline completion,
--   -- blink.cmp select_prev, blink.cmp accept), so use <C-l>/<C-]> — both
--   -- free in insert mode (<C-l> is only bound in normal mode, for window nav).
--   accept_keymap = '<C-l>',
--   dismiss_keymap = '<C-]>',
--   debounce_ms = 800,
--   suggestion_color = { gui = '#ff00ff', cterm = 201 }, -- loud magenta, temporary: was #808080/244 (gray), too easy to mistake for "not working"
--   exclude_filetypes = { 'TelescopePrompt' },
--   minimum_prefix_length = 2,
-- }
